export enum FOCUS_MODE {
	FOCUS_NONE = 0,
	FOCUS_CLICK = 1,
	FOCUS_ALL = 2,
}

export enum GROW_DIRECTION {
	GROW_DIRECTION_BEGIN = 0,
	GROW_DIRECTION_END = 1,
	GROW_DIRECTION_BOTH = 2,
}

export enum LAYOUT_DIRECTION {
	LAYOUT_DIRECTION_INHERITED = 0,
	LAYOUT_DIRECTION_LOCALE = 1,
	LAYOUT_DIRECTION_LTR = 2,
	LAYOUT_DIRECTION_RTL = 3,
}

export enum LAYOUT_PRESET {
	PRESET_TOP_LEFT = 0,
	PRESET_TOP_RIGHT = 1,
	PRESET_BOTTOM_LEFT = 2,
	PRESET_BOTTOM_RIGHT = 3,
	PRESET_CENTER_LEFT = 4,
	PRESET_CENTER_TOP = 5,
	PRESET_CENTER_RIGHT = 6,
	PRESET_CENTER_BOTTOM = 7,
	PRESET_CENTER = 8,
	PRESET_LEFT_WIDE = 9,
	PRESET_TOP_WIDE = 10,
	PRESET_RIGHT_WIDE = 11,
	PRESET_BOTTOM_WIDE = 12,
	PRESET_VCENTER_WIDE = 13,
	PRESET_HCENTER_WIDE = 14,
	PRESET_FULL_RECT = 15,
}

export enum MOUSE_FILTER {
	MOUSE_FILTER_STOP = 0,
	MOUSE_FILTER_PASS = 1,
	MOUSE_FILTER_IGNORE = 2,
}

export enum CURSOR_SHAPE {
	CURSOR_ARROW = 0,
	CURSOR_IBEAM = 1,
	CURSOR_POINTING_HAND = 2,
	CURSOR_CROSS = 3,
	CURSOR_WAIT = 4,
	CURSOR_BUSY = 5,
	CURSOR_DRAG = 6,
	CURSOR_CAN_DROP = 7,
	CURSOR_FORBIDDEN = 8,
	CURSOR_VSIZE = 9,
	CURSOR_HSIZE = 10,
	CURSOR_BDIAGSIZE = 11,
	CURSOR_FDIAGSIZE = 12,
	CURSOR_MOVE = 13,
	CURSOR_VSPLIT = 14,
	CURSOR_HSPLIT = 15,
	CURSOR_HELP = 16,
}

export enum SIZE_FLAGS {
	SIZE_SHRINK_BEGIN = 0,
	SIZE_FILL = 1,
	SIZE_EXPAND = 2,
	SIZE_EXPAND_FILL = 3,
	SIZE_SHRINK_CENTER = 4,
	SIZE_SHRINK_END = 8
}